### ISSUE TITLE
Unexpected content validation errors

### ISSUE THREAD

**Issue by d-swift** [spectacles-ci/spectacles#626] opened 2022-08-25 15:07 UTC
Hey, content validation is throwing a strange error and not returning any validation issues. 

Here is the output:
```
Connected to Looker version 22.12.63 using Looker API 3.1
Building LookML project hierarchy for project 'myproject' @ f5e776

=================== Validating content based on 250 explores ===================

Warning: Skipping some content because it does not seem to be a Dashboard or a Look.
Warning: Skipping some content because it does not seem to be a Dashboard or a Look.
Warning: Skipping some content because it does not seem to be a Dashboard or a Look.
Warning: Skipping some content because it does not seem to be a Dashboard or a Look.
Completed content validation in 1 minute and 23 seconds.


Encountered unexpected TypeError: "'NoneType' object is not subscriptable"
Full error traceback logged to file.

For support, please create an issue at https://github.com/spectacles-ci/spectacles/issues
```

Here is the command used:
```
spectacles content \
  --config-file config.yaml \
  --project myproject \
  --do-not-track \
```

Here is the traceback:

```2022-08-25 15:37:04,219 DEBUG | 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "/Users/username/Library/Caches/pypoetry/virtualenvs/lookoverhere-ZKlKpy3y-py3.10/lib/python3.10/site-packages/spectacles/cli.py", line 153, in wrapper
    return function(*args, **kwargs)
  File "/Users/username/Library/Caches/pypoetry/virtualenvs/lookoverhere-ZKlKpy3y-py3.10/lib/python3.10/site-packages/spectacles/cli.py", line 307, in main
    run_content(
  File "/Users/username/Library/Caches/pypoetry/virtualenvs/lookoverhere-ZKlKpy3y-py3.10/lib/python3.10/site-packages/spectacles/utils.py", line 61, in timed_function
    result = fn(*args, **kwargs)
  File "/Users/username/Library/Caches/pypoetry/virtualenvs/lookoverhere-ZKlKpy3y-py3.10/lib/python3.10/site-packages/spectacles/cli.py", line 783, in run_content
    results = runner.validate_content(
  File "/Users/username/Library/Caches/pypoetry/virtualenvs/lookoverhere-ZKlKpy3y-py3.10/lib/python3.10/site-packages/spectacles/runner.py", line 467, in validate_content
    validator.validate(project)
  File "/Users/username/Library/Caches/pypoetry/virtualenvs/lookoverhere-ZKlKpy3y-py3.10/lib/python3.10/site-packages/spectacles/validators/content.py", line 69, in validate
    errors = self._get_errors_from_result(project, content, content_type)
  File "/Users/username/Library/Caches/pypoetry/virtualenvs/lookoverhere-ZKlKpy3y-py3.10/lib/python3.10/site-packages/spectacles/validators/content.py", line 147, in _get_errors_from_result
    space=result[content_type]["space"]["name"],
TypeError: 'NoneType' object is not subscriptable
```

**Comment by joshtemple** [comment] 2022-08-25 15:56
Hey @d-swift, can you update to the release candidate for the next version of Spectacles and try again?
```
pip install spectacles==2.3.0rc3
```

**Comment by joshtemple** [comment] 2022-08-25 15:57
I believe this is a duplicate of #610.

**Comment by joshtemple** [comment] 2022-08-25 19:35
Thanks @d-swift! Looks like we can't always rely on those content objects having a title. I wish we had better guarantees from the Looker API about this sort of thing, but we don't.

I'll get a fix written for this as soon as possible. If it's something you need sooner, I'd also definitely accept a PR! It should be a quick fix to use `.get('title')` instead of `['title']`

**Comment by DylanBaker** [comment] 2023-07-17 15:46
Closing as duplicate.

**Closed by DylanBaker** 2023-07-17 15:46 UTC
Labels: Bug
